import java.sql.Connection;
import java.sql.DriverManager;
import java.util.*;

import domain.User;
import repositories.IRepository;
import repositories.IRepositoryCatalog;
import repositories.impl.DummyRepositoryCatalog;
import repositories.impl.UserRepository;

public class Main {


	public static void main(String[] args) {

		String url ="jdbc:hsqldb:hsql://localhost/workdb";
		
		User jnowak = new User();
		jnowak.setLogin("aurbanow");
		jnowak.setPassword("qwerty");
		
		try 
		{
			Connection connection = DriverManager.getConnection(url);
			/*
			  String createTable =
			 
					"CREATE TABLE users("
					+ "id int GENERATED BY DEFAULT AS IDENTITY,"
					+ "login VARCHAR(20),"
					+ "password VARCHAR(20)"
					+ ")";
			Statement stmt = connection.createStatement();
			stmt.executeUpdate(createTable);
			*/
			IRepository<User> users = new UserRepository(connection);
			users.save(jnowak);
			List<User> usersFromDb = users.getAll();
			
			for(User userFromDb : usersFromDb)
				System.out.println(userFromDb.getId()+" "+userFromDb.getLogin()+" "+userFromDb.getPassword());
			User user = users.get(1);
			user.setPassword("1qaz2wsx");
			users.update(user);
			users.delete(usersFromDb.get(0));
			for(User userFromDb : users.getAll())
				System.out.println(userFromDb.getId()+" "+userFromDb.getLogin()+" "+userFromDb.getPassword());
			
			
		} catch (Exception e) {
			e.printStackTrace();
		}
		System.out.println("koniec");
	}

}
